{% set name = "dukpy" %}
{% set version = "0.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/amol-/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 4a79269aeca6ce446a5af7db3f6158a2e24d03c155d6af43f3b3f552306a6856


build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - dukpy-install=dukpy.install:main
    - dukpy=dukpy.run:main

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - webassets
  run:
    - python
    - webassets

test:
  imports:
    - dukpy
  commands:
    - dukpy -h

about:
  home: https://github.com/amol-/dukpy
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A simple javascript interpreter for Python

  description: |
    DukPy is a simple javascript interpreter for Python built on top of duktape engine without any external dependency. 

  doc_url: https://github.com/amol-/dukpy
  dev_url: https://github.com/amol-/dukpy

extra:
  recipe-maintainers:
    - pvanheus
