{% set name = "dukpy" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/amol-/{{ name }}/archive/{{ version }}.tar.gz
  sha256: a31c0459f05660612888ab8891d221d3ba3c24172b42ac9ff7ad667dad351c45


build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - dukpy-install=dukpy.install:main
    - dukpy=dukpy.run:main

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - webassets
  run:
    - python
    - webassets

test:
  imports:
    - dukpy
  commands:
    - dukpy -h

about:
  home: https://github.com/amol-/dukpy
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A simple javascript interpreter for Python

  description: |
    DukPy is a simple javascript interpreter for Python built on top of duktape engine without any external dependency. 

  doc_url: https://github.com/amol-/dukpy
  dev_url: https://github.com/amol-/dukpy

extra:
  recipe-maintainers:
    - pvanheus
