{% set name = "dukpy" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/amol-/{{ name }}/archive/{{ version }}.tar.gz
  sha256: b1a518a758109bbefe202d6b5c98ed4d2c84c5b2e9c777ec787343dbb8d6579d


build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - dukpy-install=dukpy.install:main
    - dukpy=dukpy.run:main

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - clang =14                        # [arm64]
  host:
    - python
    - pip
    - webassets
    - setuptools  # [osx and arm64]
  run:
    - python
    - webassets

test:
  imports:
    - dukpy
  commands:
    - dukpy -h

about:
  home: https://github.com/amol-/dukpy
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A simple javascript interpreter for Python

  description: |
    DukPy is a simple javascript interpreter for Python built on top of duktape engine without any external dependency. 

  doc_url: https://github.com/amol-/dukpy
  dev_url: https://github.com/amol-/dukpy

extra:
  recipe-maintainers:
    - pvanheus
